const SUPABASE_URL ="https://pvuvfqghsqcjoeaawepg.supabase.co"
const SUPABASE_ANON_KEY= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2dXZmcWdoc3Fjam9lYWF3ZXBnIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NjM1MzgxNTEsImV4cCI6MTk3OTExNDE1MX0.3LWQHG574CL-uKJx18Cv65jfbAJz3PhKKDUyLu9px4o"

const _supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);